#!/bin/bash

random_colorize() {
    local COLORS=("31" "32" "33" "34" "35" "36" "37")
    awk -v colors="${COLORS[*]}" '
    BEGIN {
        split(colors, colorArray, " ")
        srand()
    }
    {
        color = colorArray[int(rand() * length(colorArray)) + 1]
        printf "\033[1;%sm%s\033[0m\n", color, $0
    }'
}

# Call the function to be used as a pipe
random_colorize
